sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - maven_central
build:
  runnerOs: ubuntu-latest
  freeDiskSpace: false
  exasolDbVersions:
    - "8.34.0"
    - "7.1.30"
