sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - maven_central
linkReplacements:
  - "http://www.snakeyaml.org|https://bitbucket.org/asomov/snakeyaml/src/master/"
