sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - maven_central
build:
  runnerOs: ubuntu-latest
  freeDiskSpace: false
  exasolDbVersions:
    - "2026.1.1" # Latest version
    - "2025.1.16" # Latest LTS version
    - "8.29.13" # Latest 8.x LTS version
