language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: exasol
    token:
      secure: "q1a8Sf4x5BPtmKx1b4H/e9a1zit+hSkKWj1r2HZrkPNabITpIqB5FVSoyx0BTEnB1XFEHH7ISw7zLo6h0AJ2XNox4k3mA82cZ/i2SLFqmoaf+A5PvQZzq7ZfKi7uj1OCM2DCqkNB9HP5agn7gjTzxSYszEFFhTrR2Sr+okrEnJNQ5snuV+mYvgkIRcRkuzlltfhKicxOsx7tXWrk+pvIdbdLoLdQyliBc3V/qdvEEDadpVeE30c4hbWYU7StbSpMZ7VHgrfMwqzXweR/GboISMTUh9a9WB2qKXv9ImhIUE9RNrTeOuBzgkYNYUADtKhL5jis/h97TJfkusKbR5Cw32IbIZIm46+Bs0en2yJNKsQAmXR+h3iUbG0RIFma5yCv1shN1MNRPWrhbltWhRdeXHCaElGDgiZAW8Yl0OPKQxx2aCRp9klqzo8IMfRQ0djXKTUcaHlo67TWZrYxpckeBHXHyj8cCUIwsTA33rcQLN+5X4j8+rySVqMFbYLda3ADFdhjY6GkJMDLtpdYXnLfo48J3zKewTJFcL0YoCTi5HPhNohiqNXPTZ62mKkFc+mXFuTv2UtU1iMlCTt4xi4xkb0au0hB/XNcbT3WhF7jIJ9RLpxvmMMvr1NZWdREJcslH8WbpdXWMiGKyZjDJ17/i7gj2wQsD8wmDrv4AxdzXeU="

install:
  - travis_retry mvn dependency:resolve

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - "$HOME/.m2"